PHP Syntax Fixes
Codeception/phpunit-wrapper pull request #30
Opened 2018-05-13 14:13 UTC by fishfacemcgee

After running across #28, I did some more digging and hit a few more instances of missing `string` return types for toString overrides. I installed phpstan to see if I could catch anything else, and that's how I found the `getFilteredStackTrace` call. However, most of the issues phpstan is reporting are due to this repo referencing code from Codeception/Codeception, so I opted to not include phpstan in this PR.

2018-05-13 20:53 UTC, Naktibalda requested changes
Please rebase this branch on 7.0, because your pull request is in conflict after merging #28

2018-05-14 03:47 UTC, fishfacemcgee commented
@Naktibalda Updated. Thanks for taking a look so quickly.

2018-05-14 10:11 UTC, DavertMik commented
Thanks

2018-05-14 10:11 UTC, DavertMik approved these changes

2018-05-16 19:49 UTC, fishfacemcgee commented
@Naktibalda @DavertMik Sorry to bother, but is there a rough ETA on when this PR could get merged and a new release pushed out? Assuming, of course, there aren't any lingering issues with the PR. Thanks in advance!

2018-05-17 08:30 UTC, merged

2018-05-17 08:34 UTC, Naktibalda commented
I tagged 7.1.2 release with all these changes.

2018-05-17 10:15 UTC, fishfacemcgee commented
Thanks!